environment:
  global:
    CI: true

  matrix:
    - nodejs_version: "8"     # latest 8
    - nodejs_version: "7"     # latest 7
    - nodejs_version: "9"     # latest 9

# build version format
version: "{build}"

cache:
  - '%APPDATA%\npm-cache' # npm cache
  - node_modules -> package.json # better point to npm-shrinkwrap.json or package-lock.json

install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn install

# no appveyor build step for js project
build: off

test_script:
  - node --version
  - yarn --version
  - yarn test

after_test:
  - yarn build
