language: node_js
after_success:
  - "[ -f ./coverage/lcov.info ] && cat ./coverage/lcov.info | coveralls"
node_js:
  - "8"
  - "9"

before_install:
  # - npm install -g npm # update to the latest npm to enable lock file usage
  - yarn global add greenkeeper-lockfile@1
  - yarn global add coveralls
before_script: greenkeeper-lockfile-update

cache:
  directories:
    - node_modules
script:
  - yarn test --coverage
  - yarn build

# Only the node version 8 job will upload the lockfile
after_script: greenkeeper-lockfile-upload
