language: node_js
after_success:
  - "[ -f ./coverage/lcov.info ] && cat ./coverage/lcov.info | coveralls"
node_js:
  - "8"
  - "7"
  - "6"

before_install:
  - npm install -g npm # update to the lates npm to enable lock file usage
  - npm install -g greenkeeper-lockfile@1
  - npm install -g coveralls
before_script: greenkeeper-lockfile-update

cache:
  directories:
    - node_modules
script:
  - npm test -- --coverage
  - npm run build

# Only the node version 8 job will upload the lockfile
after_script: greenkeeper-lockfile-upload
